/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppShopRouteImport } from './routes/_app.shop'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPollsRouteImport } from './routes/_app.polls'
import { Route as AppMessengerRouteImport } from './routes/_app.messenger'
import { Route as AppLinksRouteImport } from './routes/_app.links'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCartRouteImport } from './routes/_app.cart'
import { Route as AppBonusesRouteImport } from './routes/_app.bonuses'
import { Route as AppBirthdaysRouteImport } from './routes/_app.birthdays'
import { Route as AppAdminRouteImport } from './routes/_app.admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPollsRoute = AppPollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => AppRoute,
} as any)
const AppMessengerRoute = AppMessengerRouteImport.update({
  id: '/messenger',
  path: '/messenger',
  getParentRoute: () => AppRoute,
} as any)
const AppLinksRoute = AppLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppBonusesRoute = AppBonusesRouteImport.update({
  id: '/bonuses',
  path: '/bonuses',
  getParentRoute: () => AppRoute,
} as any)
const AppBirthdaysRoute = AppBirthdaysRouteImport.update({
  id: '/birthdays',
  path: '/birthdays',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/birthdays': typeof AppBirthdaysRoute
  '/bonuses': typeof AppBonusesRoute
  '/cart': typeof AppCartRoute
  '/dashboard': typeof AppDashboardRoute
  '/home': typeof AppHomeRoute
  '/jobs': typeof AppJobsRoute
  '/links': typeof AppLinksRoute
  '/messenger': typeof AppMessengerRoute
  '/polls': typeof AppPollsRoute
  '/profile': typeof AppProfileRoute
  '/shop': typeof AppShopRoute
  '/team': typeof AppTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/birthdays': typeof AppBirthdaysRoute
  '/bonuses': typeof AppBonusesRoute
  '/cart': typeof AppCartRoute
  '/dashboard': typeof AppDashboardRoute
  '/home': typeof AppHomeRoute
  '/jobs': typeof AppJobsRoute
  '/links': typeof AppLinksRoute
  '/messenger': typeof AppMessengerRoute
  '/polls': typeof AppPollsRoute
  '/profile': typeof AppProfileRoute
  '/shop': typeof AppShopRoute
  '/team': typeof AppTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/birthdays': typeof AppBirthdaysRoute
  '/_app/bonuses': typeof AppBonusesRoute
  '/_app/cart': typeof AppCartRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/links': typeof AppLinksRoute
  '/_app/messenger': typeof AppMessengerRoute
  '/_app/polls': typeof AppPollsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/shop': typeof AppShopRoute
  '/_app/team': typeof AppTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/birthdays'
    | '/bonuses'
    | '/cart'
    | '/dashboard'
    | '/home'
    | '/jobs'
    | '/links'
    | '/messenger'
    | '/polls'
    | '/profile'
    | '/shop'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/birthdays'
    | '/bonuses'
    | '/cart'
    | '/dashboard'
    | '/home'
    | '/jobs'
    | '/links'
    | '/messenger'
    | '/polls'
    | '/profile'
    | '/shop'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/birthdays'
    | '/_app/bonuses'
    | '/_app/cart'
    | '/_app/dashboard'
    | '/_app/home'
    | '/_app/jobs'
    | '/_app/links'
    | '/_app/messenger'
    | '/_app/polls'
    | '/_app/profile'
    | '/_app/shop'
    | '/_app/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shop': {
      id: '/_app/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/polls': {
      id: '/_app/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof AppPollsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messenger': {
      id: '/_app/messenger'
      path: '/messenger'
      fullPath: '/messenger'
      preLoaderRoute: typeof AppMessengerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/links': {
      id: '/_app/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AppLinksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cart': {
      id: '/_app/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bonuses': {
      id: '/_app/bonuses'
      path: '/bonuses'
      fullPath: '/bonuses'
      preLoaderRoute: typeof AppBonusesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/birthdays': {
      id: '/_app/birthdays'
      path: '/birthdays'
      fullPath: '/birthdays'
      preLoaderRoute: typeof AppBirthdaysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBirthdaysRoute: typeof AppBirthdaysRoute
  AppBonusesRoute: typeof AppBonusesRoute
  AppCartRoute: typeof AppCartRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHomeRoute: typeof AppHomeRoute
  AppJobsRoute: typeof AppJobsRoute
  AppLinksRoute: typeof AppLinksRoute
  AppMessengerRoute: typeof AppMessengerRoute
  AppPollsRoute: typeof AppPollsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppShopRoute: typeof AppShopRoute
  AppTeamRoute: typeof AppTeamRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBirthdaysRoute: AppBirthdaysRoute,
  AppBonusesRoute: AppBonusesRoute,
  AppCartRoute: AppCartRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHomeRoute: AppHomeRoute,
  AppJobsRoute: AppJobsRoute,
  AppLinksRoute: AppLinksRoute,
  AppMessengerRoute: AppMessengerRoute,
  AppPollsRoute: AppPollsRoute,
  AppProfileRoute: AppProfileRoute,
  AppShopRoute: AppShopRoute,
  AppTeamRoute: AppTeamRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
